[tool.poetry]
name = "github-pokemon-collection"
version = "4"
description = ""
authors = ["2jun0 <soo28819@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.1"
pydantic-settings = "^2.2.1"
sqlmodel = "^0.0.22"
pydantic-core = "^2.18.1"
uvicorn = "^0.29.0"
greenlet = "^3.0.3"
asyncpg = "^0.29.0"
httpx = "^0.27.0"
h2 = "^4.1.0"
tqdm = "^4.66.4"
aiofiles = "^24.1.0"
httpx-oauth = "^0.15.1"
pyjwt = "^2.9.0"
pytz = "^2024.1"


[tool.poetry.group.dev.dependencies]
aiosqlite = "^0.20.0"
pytest-asyncio = "^0.23.6"
pytest = "^8.1.1"
alembic = "^1.13.1"
pytest-env = "^1.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 119
experimental-string-processing = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''