"""0007-add-index-to-foreign-keys

Revision ID: 09eaf098922d
Revises: 375bfff70c14
Create Date: 2024-09-10 16:26:51.277897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09eaf098922d'
down_revision: Union[str, None] = '375bfff70c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bag_item_owner_id'), 'bag_item', ['owner_id'], unique=False)
    op.create_index(op.f('ix_commit_point_user_id'), 'commit_point', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_item_abtain_daily_item_id'), 'daily_item_abtain', ['daily_item_id'], unique=False)
    op.create_index(op.f('ix_daily_item_abtain_user_id'), 'daily_item_abtain', ['user_id'], unique=False)
    op.create_index(op.f('ix_pokedex_item_owner_id'), 'pokedex_item', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pokemon_owner_id'), 'pokemon', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_owner_id'), table_name='pokemon')
    op.drop_index(op.f('ix_pokedex_item_owner_id'), table_name='pokedex_item')
    op.drop_index(op.f('ix_daily_item_abtain_user_id'), table_name='daily_item_abtain')
    op.drop_index(op.f('ix_daily_item_abtain_daily_item_id'), table_name='daily_item_abtain')
    op.drop_index(op.f('ix_commit_point_user_id'), table_name='commit_point')
    op.drop_index(op.f('ix_bag_item_owner_id'), table_name='bag_item')
    # ### end Alembic commands ###
