"""0002-ADD-IS-SHINY-FIELD

Revision ID: 355bcc98cde5
Revises: 7c311b657452
Create Date: 2024-05-01 20:17:32.733147

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "355bcc98cde5"
down_revision: Union[str, None] = "7c311b657452"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pokemon", sa.Column("is_shiny", sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemon", "is_shiny")
    # ### end Alembic commands ###
