"""0006

Revision ID: 375bfff70c14
Revises: d08ddf4152ff
Create Date: 2024-09-10 16:12:11.749021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '375bfff70c14'
down_revision: Union[str, None] = 'd08ddf4152ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bag_item_owner_id_fkey', 'bag_item', type_='foreignkey')
    op.create_foreign_key(None, 'bag_item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('commit_point_user_id_fkey', 'commit_point', type_='foreignkey')
    op.create_foreign_key(None, 'commit_point', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('pokedex_item_owner_id_fkey', 'pokedex_item', type_='foreignkey')
    op.create_foreign_key(None, 'pokedex_item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'pokemon', ['owner_id', 'type'])
    op.drop_constraint('pokemon_owner_id_fkey', 'pokemon', type_='foreignkey')
    op.create_foreign_key(None, 'pokemon', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.create_foreign_key('pokemon_owner_id_fkey', 'pokemon', 'user', ['owner_id'], ['id'])
    op.drop_constraint(None, 'pokemon', type_='unique')
    op.drop_constraint(None, 'pokedex_item', type_='foreignkey')
    op.create_foreign_key('pokedex_item_owner_id_fkey', 'pokedex_item', 'user', ['owner_id'], ['id'])
    op.drop_constraint(None, 'commit_point', type_='foreignkey')
    op.create_foreign_key('commit_point_user_id_fkey', 'commit_point', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'bag_item', type_='foreignkey')
    op.create_foreign_key('bag_item_owner_id_fkey', 'bag_item', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
