from typing import Literal

from pydantic import BaseModel, Field

from src.models.pokemon import Pokemon
from src.models.pokemon_type import PokemonType
from src.pokemons.item import Item


class EvolutionRule(BaseModel):
    to: PokemonType
    required_level: int = Field(default=0)
    required_item: None | str = Field(default=None)
    required_time: Literal["day", "night"] = Field(default=None)
    required_frendship: int = Field(default=0)

    def is_met(self, pokemon: Pokemon):
        if self.required_level > pokemon.level:
            return False


evolution_rules = {
    PokemonType.Bulbasaur: (EvolutionRule(to=PokemonType.Ivysaur, required_level=16),),
    PokemonType.Ivysaur: (EvolutionRule(to=PokemonType.Venusaur, required_level=32),),
    PokemonType.Charmander: (EvolutionRule(to=PokemonType.Charmeleon, required_level=16),),
    PokemonType.Charmeleon: (EvolutionRule(to=PokemonType.Charizard, required_level=36),),
    PokemonType.Squirtle: (EvolutionRule(to=PokemonType.Wartortle, required_level=16),),
    PokemonType.Wartortle: (EvolutionRule(to=PokemonType.Blastoise, required_level=36),),
    PokemonType.Caterpie: (EvolutionRule(to=PokemonType.Metapod, required_level=7),),
    PokemonType.Metapod: (EvolutionRule(to=PokemonType.Butterfree, required_level=10),),
    PokemonType.Weedle: (EvolutionRule(to=PokemonType.Kakuna, required_level=7),),
    PokemonType.Kakuna: (EvolutionRule(to=PokemonType.Beedrill, required_level=10),),
    PokemonType.Pidgey: (EvolutionRule(to=PokemonType.Pidgeotto, required_level=18),),
    PokemonType.Pidgeotto: (EvolutionRule(to=PokemonType.Pidgeot, required_level=36),),
    PokemonType.Rattata: (EvolutionRule(to=PokemonType.Raticate, required_level=20),),
    PokemonType.Spearow: (EvolutionRule(to=PokemonType.Fearow, required_level=20),),
    PokemonType.Ekans: (EvolutionRule(to=PokemonType.Arbok, required_level=22),),
    PokemonType.Pikachu: (EvolutionRule(to=PokemonType.Raichu, required_item=Item.THUNDER_STONE),),
    PokemonType.Sandshrew: (EvolutionRule(to=PokemonType.Sandslash, required_level=22),),
    PokemonType.Nidoran_female: (EvolutionRule(to=PokemonType.Nidorina, required_level=16),),
    PokemonType.Nidorina: (EvolutionRule(to=PokemonType.Nidoqueen, required_item=Item.MOON_STONE),),
    PokemonType.Nidoran_male: (EvolutionRule(to=PokemonType.Nidorino, required_level=16),),
    PokemonType.Nidorino: (EvolutionRule(to=PokemonType.Nidoking, required_item=Item.MOON_STONE),),
    PokemonType.Clefairy: (EvolutionRule(to=PokemonType.Clefable, required_item=Item.MOON_STONE),),
    PokemonType.Vulpix: (EvolutionRule(to=PokemonType.Ninetales, required_item=Item.FIRE_STONE),),
    PokemonType.Jigglypuff: (EvolutionRule(to=PokemonType.Wigglytuff, required_item=Item.MOON_STONE),),
    PokemonType.Zubat: (EvolutionRule(to=PokemonType.Golbat, required_level=22),),
    PokemonType.Golbat: (EvolutionRule(to=PokemonType.Crobat, required_frendship=220),),
    PokemonType.Oddish: (EvolutionRule(to=PokemonType.Gloom, required_level=22),),
    PokemonType.Gloom: (
        EvolutionRule(to=PokemonType.Vileplume, required_item=Item.LEAF_STONE),
        EvolutionRule(to=PokemonType.Bellossom, required_item=Item.SUN_STONE),
    ),
    PokemonType.Paras: (EvolutionRule(to=PokemonType.Parasect, required_level=24),),
    PokemonType.Venonat: (EvolutionRule(to=PokemonType.Venomoth, required_level=31),),
    PokemonType.Diglett: (EvolutionRule(to=PokemonType.Dugtrio, required_level=26),),
    PokemonType.Meowth: (EvolutionRule(to=PokemonType.Persian, required_level=28),),
    PokemonType.Psyduck: (EvolutionRule(to=PokemonType.Golduck, required_level=33),),
    PokemonType.Mankey: (EvolutionRule(to=PokemonType.Primeape, required_level=28),),
    PokemonType.Growlithe: (EvolutionRule(to=PokemonType.Arcanine, required_item=Item.FIRE_STONE),),
    PokemonType.Poliwag: (EvolutionRule(to=PokemonType.Poliwhirl, required_level=25),),
    PokemonType.Poliwhirl: (
        EvolutionRule(to=PokemonType.Poliwrath, required_item=Item.WATER_STONE),
        EvolutionRule(to=PokemonType.Politoed, required_item=Item.KINGS_ROCK),
    ),
    PokemonType.Abra: (EvolutionRule(to=PokemonType.Kadabra, required_level=16),),
    PokemonType.Kadabra: (EvolutionRule(to=PokemonType.Alakazam, required_item=Item.LINKING_CORD),),
    PokemonType.Machop: (EvolutionRule(to=PokemonType.Machoke, required_level=28),),
    PokemonType.Machoke: (EvolutionRule(to=PokemonType.Machamp, required_item=Item.LINKING_CORD),),
    PokemonType.Bellsprout: (EvolutionRule(to=PokemonType.Weepinbell, required_level=21),),
    PokemonType.Weepinbell: (EvolutionRule(to=PokemonType.Victreebel, required_item=Item.LEAF_STONE),),
    PokemonType.Tentacool: (EvolutionRule(to=PokemonType.Tentacruel, required_level=30),),
    PokemonType.Geodude: (EvolutionRule(to=PokemonType.Graveler, required_level=25),),
    PokemonType.Graveler: (EvolutionRule(to=PokemonType.Golem, required_item=Item.LINKING_CORD),),
    PokemonType.Ponyta: (EvolutionRule(to=PokemonType.Rapidash, required_level=40),),
    PokemonType.Slowpoke: (
        EvolutionRule(to=PokemonType.Slowbro, required_level=37),
        EvolutionRule(to=PokemonType.Slowking, required_item=Item.KINGS_ROCK),
    ),
    PokemonType.Magnemite: (EvolutionRule(to=PokemonType.Magneton, required_level=30),),
    PokemonType.Magneton: (EvolutionRule(to=PokemonType.Magnezone, required_item=Item.THUNDER_STONE),),
    PokemonType.Doduo: (EvolutionRule(to=PokemonType.Dodrio, required_level=31),),
    PokemonType.Seel: (EvolutionRule(to=PokemonType.Dewgong, required_level=34),),
    PokemonType.Grimer: (EvolutionRule(to=PokemonType.Muk, required_level=38),),
    PokemonType.Shellder: (EvolutionRule(to=PokemonType.Cloyster, required_item=Item.WATER_STONE),),
    PokemonType.Gastly: (EvolutionRule(to=PokemonType.Haunter, required_level=25),),
    PokemonType.Haunter: (EvolutionRule(to=PokemonType.Gengar, required_item=Item.LINKING_CORD),),
    PokemonType.Onix: (EvolutionRule(to=PokemonType.Steelix, required_item=Item.METAL_COAT),),
    PokemonType.Drowzee: (EvolutionRule(to=PokemonType.Hypno, required_level=26),),
    PokemonType.Krabby: (EvolutionRule(to=PokemonType.Kingler, required_level=28),),
    PokemonType.Voltorb: (EvolutionRule(to=PokemonType.Electrode, required_level=30),),
    PokemonType.Exeggcute: (EvolutionRule(to=PokemonType.Exeggutor, required_item=Item.LEAF_STONE),),
    PokemonType.Cubone: (EvolutionRule(to=PokemonType.Marowak, required_level=28),),
    PokemonType.Lickitung: (EvolutionRule(to=PokemonType.Lickilicky, required_level=33),),
    PokemonType.Koffing: (EvolutionRule(to=PokemonType.Weezing, required_level=35),),
    PokemonType.Rhyhorn: (EvolutionRule(to=PokemonType.Rhydon, required_level=42),),
    PokemonType.Rhydon: (EvolutionRule(to=PokemonType.Rhyperior, required_item=Item.PROTECTOR),),
    PokemonType.Chansey: (EvolutionRule(to=PokemonType.Blissey, required_frendship=220),),
    PokemonType.Tangela: (EvolutionRule(to=PokemonType.Tangrowth, required_level=33),),
    PokemonType.Horsea: (EvolutionRule(to=PokemonType.Seadra, required_level=32),),
    PokemonType.Seadra: (EvolutionRule(to=PokemonType.Kingdra, required_item=Item.DRAGON_SCALE),),
    PokemonType.Goldeen: (EvolutionRule(to=PokemonType.Seaking, required_level=33),),
    PokemonType.Staryu: (EvolutionRule(to=PokemonType.Starmie, required_item=Item.WATER_STONE),),
    PokemonType.Scyther: (EvolutionRule(to=PokemonType.Scizor, required_item=Item.METAL_COAT),),
    PokemonType.Electabuzz: (EvolutionRule(to=PokemonType.Electivire, required_item=Item.ELECTIRIZER),),
    PokemonType.Magmar: (EvolutionRule(to=PokemonType.Magmortar, required_item=Item.MAGMARIZER),),
    PokemonType.Magikarp: (EvolutionRule(to=PokemonType.Gyarados, required_level=20),),
    PokemonType.Eevee: (
        EvolutionRule(to=PokemonType.Vaporeon, required_item=Item.WATER_STONE),
        EvolutionRule(to=PokemonType.Jolteon, required_item=Item.THUNDER_STONE),
        EvolutionRule(to=PokemonType.Flareon, required_item=Item.FIRE_STONE),
        EvolutionRule(to=PokemonType.Espeon, required_frendship=160, required_time="day"),
        EvolutionRule(to=PokemonType.Umbreon, required_frendship=160, required_time="night"),
        EvolutionRule(to=PokemonType.Leafeon, required_item=Item.LEAF_STONE),
        EvolutionRule(to=PokemonType.Glaceon, required_item=Item.ICE_STONE),
    ),
    PokemonType.Porygon: (EvolutionRule(to=PokemonType.Porygon2, required_item=Item.UP_GRADE),),
    PokemonType.Omanyte: (EvolutionRule(to=PokemonType.Omastar, required_level=40),),
    PokemonType.Kabuto: (EvolutionRule(to=PokemonType.Kabutops, required_level=40),),
    PokemonType.Dratini: (EvolutionRule(to=PokemonType.Dragonair, required_level=30),),
    PokemonType.Dragonair: (EvolutionRule(to=PokemonType.Dragonite, required_level=55),),
    PokemonType.Chikorita: (EvolutionRule(to=PokemonType.Bayleef, required_level=16),),
    PokemonType.Bayleef: (EvolutionRule(to=PokemonType.Meganium, required_level=32),),
    PokemonType.Cyndaquil: (EvolutionRule(to=PokemonType.Quilava, required_level=14),),
    PokemonType.Quilava: (EvolutionRule(to=PokemonType.Typhlosion, required_level=36),),
    PokemonType.Totodile: (EvolutionRule(to=PokemonType.Croconaw, required_level=18),),
    PokemonType.Croconaw: (EvolutionRule(to=PokemonType.Feraligatr, required_level=30),),
    PokemonType.Sentret: (EvolutionRule(to=PokemonType.Furret, required_level=15),),
    PokemonType.Hoothoot: (EvolutionRule(to=PokemonType.Noctowl, required_level=20),),
    PokemonType.Ledyba: (EvolutionRule(to=PokemonType.Ledian, required_level=18),),
    PokemonType.Spinarak: (EvolutionRule(to=PokemonType.Ariados, required_level=22),),
    PokemonType.Chinchou: (EvolutionRule(to=PokemonType.Lanturn, required_level=27),),
    PokemonType.Pichu: (EvolutionRule(to=PokemonType.Pikachu, required_frendship=220),),
    PokemonType.Cleffa: (EvolutionRule(to=PokemonType.Clefairy, required_frendship=220),),
    PokemonType.Igglybuff: (EvolutionRule(to=PokemonType.Jigglypuff, required_frendship=220),),
    PokemonType.Togepi: (EvolutionRule(to=PokemonType.Togetic, required_frendship=220),),
    PokemonType.Togetic: (EvolutionRule(to=PokemonType.Togekiss, required_item=Item.SHINY_STONE),),
    PokemonType.Natu: (EvolutionRule(to=PokemonType.Xatu, required_level=25),),
    PokemonType.Mareep: (EvolutionRule(to=PokemonType.Flaaffy, required_level=15),),
    PokemonType.Flaaffy: (EvolutionRule(to=PokemonType.Ampharos, required_level=30),),
    PokemonType.Marill: (EvolutionRule(to=PokemonType.Azumarill, required_level=18),),
    PokemonType.Hoppip: (EvolutionRule(to=PokemonType.Skiploom, required_level=18),),
    PokemonType.Skiploom: (EvolutionRule(to=PokemonType.Jumpluff, required_level=27),),
    PokemonType.Aipom: (EvolutionRule(to=PokemonType.Ambipom, required_level=32),),
    PokemonType.Sunkern: (EvolutionRule(to=PokemonType.Sunflora, required_item=Item.SUN_STONE),),
    PokemonType.Wooper: (EvolutionRule(to=PokemonType.Quagsire, required_level=20),),
    PokemonType.Murkrow: (EvolutionRule(to=PokemonType.Honchkrow, required_item=Item.DUSK_STONE),),
    PokemonType.Misdreavus: (EvolutionRule(to=PokemonType.Mismagius, required_item=Item.DUSK_STONE),),
    PokemonType.Pineco: (EvolutionRule(to=PokemonType.Forretress, required_level=31),),
    PokemonType.Gligar: (EvolutionRule(to=PokemonType.Gliscor, required_item=Item.RAZOR_FANG, required_time="night"),),
    PokemonType.Snubbull: (EvolutionRule(to=PokemonType.Granbull, required_level=23),),
    PokemonType.Sneasel: (
        EvolutionRule(to=PokemonType.Weavile, required_item=Item.RAZOR_CLAW, required_time="night"),
    ),
    PokemonType.Teddiursa: (EvolutionRule(to=PokemonType.Ursaring, required_level=30),),
    PokemonType.Slugma: (EvolutionRule(to=PokemonType.Magcargo, required_level=38),),
    PokemonType.Swinub: (EvolutionRule(to=PokemonType.Piloswine, required_level=33),),
    PokemonType.Piloswine: (EvolutionRule(to=PokemonType.Mamoswine, required_level=34),),
    PokemonType.Remoraid: (EvolutionRule(to=PokemonType.Octillery, required_level=25),),
    PokemonType.Houndour: (EvolutionRule(to=PokemonType.Houndoom, required_level=24),),
    PokemonType.Phanpy: (EvolutionRule(to=PokemonType.Donphan, required_level=25),),
    PokemonType.Porygon2: (EvolutionRule(to=PokemonType.PorygonZ, required_item=Item.DUBIOUS_DISC),),
    PokemonType.Tyrogue: (
        EvolutionRule(to=PokemonType.Hitmonlee, required_level=20),
        EvolutionRule(to=PokemonType.Hitmonchan, required_level=20),
        EvolutionRule(to=PokemonType.Hitmontop, required_level=20),
    ),  # 랜덤 요소
    PokemonType.Smoochum: (EvolutionRule(to=PokemonType.Jynx, required_level=30),),
    PokemonType.Elekid: (EvolutionRule(to=PokemonType.Electabuzz, required_level=30),),
    PokemonType.Magby: (EvolutionRule(to=PokemonType.Magmar, required_level=30),),
    PokemonType.Larvitar: (EvolutionRule(to=PokemonType.Pupitar, required_level=30),),
    PokemonType.Pupitar: (EvolutionRule(to=PokemonType.Tyranitar, required_level=55),),
    PokemonType.Treecko: (EvolutionRule(to=PokemonType.Grovyle, required_level=16),),
    PokemonType.Grovyle: (EvolutionRule(to=PokemonType.Sceptile, required_level=36),),
    PokemonType.Torchic: (EvolutionRule(to=PokemonType.Combusken, required_level=16),),
    PokemonType.Combusken: (EvolutionRule(to=PokemonType.Blaziken, required_level=36),),
    PokemonType.Mudkip: (EvolutionRule(to=PokemonType.Marshtomp, required_level=16),),
    PokemonType.Marshtomp: (EvolutionRule(to=PokemonType.Swampert, required_level=36),),
    PokemonType.Poochyena: (EvolutionRule(to=PokemonType.Mightyena, required_level=18),),
    PokemonType.Zigzagoon: (EvolutionRule(to=PokemonType.Linoone, required_level=20),),
    PokemonType.Wurmple: (
        EvolutionRule(to=PokemonType.Silcoon, required_level=7),
        EvolutionRule(to=PokemonType.Cascoon, required_level=7),
    ),  # 랜덤 요소
    PokemonType.Silcoon: (EvolutionRule(to=PokemonType.Beautifly, required_level=10),),
    PokemonType.Cascoon: (EvolutionRule(to=PokemonType.Dustox, required_level=10),),
    PokemonType.Lotad: (EvolutionRule(to=PokemonType.Lombre, required_level=14),),
    PokemonType.Lombre: (EvolutionRule(to=PokemonType.Ludicolo, required_item=Item.WATER_STONE),),
    PokemonType.Seedot: (EvolutionRule(to=PokemonType.Nuzleaf, required_level=14),),
    PokemonType.Nuzleaf: (EvolutionRule(to=PokemonType.Shiftry, required_item=Item.LEAF_STONE),),
    PokemonType.Taillow: (EvolutionRule(to=PokemonType.Swellow, required_level=22),),
    PokemonType.Wingull: (EvolutionRule(to=PokemonType.Pelipper, required_level=25),),
    PokemonType.Ralts: (EvolutionRule(to=PokemonType.Kirlia, required_level=20),),
    PokemonType.Kirlia: (
        EvolutionRule(to=PokemonType.Gardevoir, required_level=30),
        EvolutionRule(to=PokemonType.Gallade, required_item=Item.DAWN_STONE),
    ),
    PokemonType.Surskit: (EvolutionRule(to=PokemonType.Masquerain, required_level=22),),
    PokemonType.Shroomish: (EvolutionRule(to=PokemonType.Breloom, required_level=23),),
    PokemonType.Slakoth: (EvolutionRule(to=PokemonType.Vigoroth, required_level=18),),
    PokemonType.Vigoroth: (EvolutionRule(to=PokemonType.Slaking, required_level=36),),
    PokemonType.Nincada: (EvolutionRule(to=PokemonType.Ninjask, required_level=20),),  # TODO: give user Shedinja too
    PokemonType.Whismur: (EvolutionRule(to=PokemonType.Loudred, required_level=20),),
    PokemonType.Loudred: (EvolutionRule(to=PokemonType.Exploud, required_level=40),),
    PokemonType.Makuhita: (EvolutionRule(to=PokemonType.Hariyama, required_level=24),),
    PokemonType.Azurill: (EvolutionRule(to=PokemonType.Marill, required_frendship=220),),
    PokemonType.Nosepass: (EvolutionRule(to=PokemonType.Probopass, required_item=Item.THUNDER_STONE),),
    PokemonType.Skitty: (EvolutionRule(to=PokemonType.Delcatty, required_item=Item.MOON_STONE),),
    PokemonType.Aron: (EvolutionRule(to=PokemonType.Lairon, required_level=32),),
    PokemonType.Lairon: (EvolutionRule(to=PokemonType.Aggron, required_level=42),),
    PokemonType.Meditite: (EvolutionRule(to=PokemonType.Medicham, required_level=37),),
    PokemonType.Electrike: (EvolutionRule(to=PokemonType.Manectric, required_level=26),),
    PokemonType.Roselia: (EvolutionRule(to=PokemonType.Roserade, required_item=Item.SHINY_STONE),),
    PokemonType.Gulpin: (EvolutionRule(to=PokemonType.Swalot, required_level=26),),
    PokemonType.Carvanha: (EvolutionRule(to=PokemonType.Sharpedo, required_level=30),),
    PokemonType.Wailmer: (EvolutionRule(to=PokemonType.Wailord, required_level=40),),
    PokemonType.Numel: (EvolutionRule(to=PokemonType.Camerupt, required_level=33),),
    PokemonType.Spoink: (EvolutionRule(to=PokemonType.Grumpig, required_level=32),),
    PokemonType.Trapinch: (EvolutionRule(to=PokemonType.Vibrava, required_level=35),),
    PokemonType.Vibrava: (EvolutionRule(to=PokemonType.Flygon, required_level=45),),
    PokemonType.Cacnea: (EvolutionRule(to=PokemonType.Cacturne, required_level=32),),
    PokemonType.Swablu: (EvolutionRule(to=PokemonType.Altaria, required_level=35),),
    PokemonType.Barboach: (EvolutionRule(to=PokemonType.Whiscash, required_level=30),),
    PokemonType.Corphish: (EvolutionRule(to=PokemonType.Crawdaunt, required_level=30),),
    PokemonType.Baltoy: (EvolutionRule(to=PokemonType.Claydol, required_level=36),),
    PokemonType.Lileep: (EvolutionRule(to=PokemonType.Cradily, required_level=40),),
    PokemonType.Anorith: (EvolutionRule(to=PokemonType.Armaldo, required_level=40),),
    PokemonType.Feebas: (EvolutionRule(to=PokemonType.Milotic, required_item=Item.PRISM_SCALE),),
    PokemonType.Shuppet: (EvolutionRule(to=PokemonType.Banette, required_level=37),),
    PokemonType.Duskull: (EvolutionRule(to=PokemonType.Dusclops, required_level=37),),
    PokemonType.Dusclops: (EvolutionRule(to=PokemonType.Dusknoir, required_item=Item.REAPER_CLOTH),),
    PokemonType.Wynaut: (EvolutionRule(to=PokemonType.Wobbuffet, required_level=15),),
    PokemonType.Snorunt: (
        EvolutionRule(to=PokemonType.Glalie, required_level=42),
        EvolutionRule(to=PokemonType.Froslass, required_item=Item.DAWN_STONE),
    ),
    PokemonType.Spheal: (EvolutionRule(to=PokemonType.Sealeo, required_level=32),),
    PokemonType.Sealeo: (EvolutionRule(to=PokemonType.Walrein, required_level=44),),
    PokemonType.Clamperl: (
        EvolutionRule(to=PokemonType.Huntail, required_item=Item.DEEP_SEA_TOOTH),
        EvolutionRule(to=PokemonType.Gorebyss, required_item=Item.DEEP_SEA_SCALE),
    ),
    PokemonType.Bagon: (EvolutionRule(to=PokemonType.Shelgon, required_level=30),),
    PokemonType.Shelgon: (EvolutionRule(to=PokemonType.Salamence, required_level=50),),
    PokemonType.Beldum: (EvolutionRule(to=PokemonType.Metang, required_level=20),),
    PokemonType.Metang: (EvolutionRule(to=PokemonType.Metagross, required_level=45),),
    PokemonType.Turtwig: (EvolutionRule(to=PokemonType.Grotle, required_level=18),),
    PokemonType.Grotle: (EvolutionRule(to=PokemonType.Torterra, required_level=32),),
    PokemonType.Chimchar: (EvolutionRule(to=PokemonType.Monferno, required_level=14),),
    PokemonType.Monferno: (EvolutionRule(to=PokemonType.Infernape, required_level=36),),
    PokemonType.Piplup: (EvolutionRule(to=PokemonType.Prinplup, required_level=16),),
    PokemonType.Prinplup: (EvolutionRule(to=PokemonType.Empoleon, required_level=36),),
    PokemonType.Starly: (EvolutionRule(to=PokemonType.Staravia, required_level=14),),
    PokemonType.Staravia: (EvolutionRule(to=PokemonType.Staraptor, required_level=34),),
    PokemonType.Bidoof: (EvolutionRule(to=PokemonType.Bibarel, required_level=15),),
    PokemonType.Kricketot: (EvolutionRule(to=PokemonType.Kricketune, required_level=10),),
    PokemonType.Shinx: (EvolutionRule(to=PokemonType.Luxio, required_level=15),),
    PokemonType.Luxio: (EvolutionRule(to=PokemonType.Luxray, required_level=30),),
    PokemonType.Budew: (EvolutionRule(to=PokemonType.Roselia, required_frendship=160, required_time="day"),),
    PokemonType.Cranidos: (EvolutionRule(to=PokemonType.Rampardos, required_level=30),),
    PokemonType.Shieldon: (EvolutionRule(to=PokemonType.Bastiodon, required_level=30),),
    PokemonType.Burmy: (
        EvolutionRule(to=PokemonType.Wormadam, required_level=20),
        EvolutionRule(to=PokemonType.Mothim, required_level=20),
    ),
    PokemonType.Combee: (EvolutionRule(to=PokemonType.Vespiquen, required_level=21),),
    PokemonType.Buizel: (EvolutionRule(to=PokemonType.Floatzel, required_level=26),),
    PokemonType.Cherubi: (EvolutionRule(to=PokemonType.Cherrim, required_level=25),),
    PokemonType.Shellos: (EvolutionRule(to=PokemonType.Gastrodon, required_level=30),),
    PokemonType.Drifloon: (EvolutionRule(to=PokemonType.Drifblim, required_level=28),),
    PokemonType.Buneary: (EvolutionRule(to=PokemonType.Lopunny, required_frendship=220),),
    PokemonType.Glameow: (EvolutionRule(to=PokemonType.Purugly, required_level=38),),
    PokemonType.Chingling: (EvolutionRule(to=PokemonType.Chimecho, required_frendship=220, required_time="night"),),
    PokemonType.Stunky: (EvolutionRule(to=PokemonType.Skuntank, required_level=34),),
    PokemonType.Bronzor: (EvolutionRule(to=PokemonType.Bronzong, required_level=33),),
    PokemonType.Bonsly: (EvolutionRule(to=PokemonType.Sudowoodo, required_level=15),),
    PokemonType.MimeJr: (EvolutionRule(to=PokemonType.MrMime, required_level=18),),
    PokemonType.Happiny: (EvolutionRule(to=PokemonType.Chansey, required_item=Item.OVAL_STONE),),
    PokemonType.Gible: (EvolutionRule(to=PokemonType.Gabite, required_level=24),),
    PokemonType.Gabite: (EvolutionRule(to=PokemonType.Garchomp, required_level=48),),
    PokemonType.Munchlax: (EvolutionRule(to=PokemonType.Snorlax, required_frendship=220),),
    PokemonType.Riolu: (EvolutionRule(to=PokemonType.Lucario, required_frendship=220, required_time="day"),),
    PokemonType.Hippopotas: (EvolutionRule(to=PokemonType.Hippowdon, required_level=34),),
    PokemonType.Skorupi: (EvolutionRule(to=PokemonType.Drapion, required_level=40),),
    PokemonType.Croagunk: (EvolutionRule(to=PokemonType.Toxicroak, required_level=37),),
    PokemonType.Finneon: (EvolutionRule(to=PokemonType.Lumineon, required_level=31),),
    PokemonType.Mantyke: (EvolutionRule(to=PokemonType.Mantine),),  # TODO: Condition that user have Remoraid
}
