from pydantic import BaseModel, Field

from src.models.pokemon import Pokemon
from src.models.user import User
from src.pokemons.item_type import ItemType
from src.pokemons.pokemon_type import PokemonType
from src.pokemons.time import Time


class EvolutionRule(BaseModel):
    to: PokemonType
    required_level: int = Field(default=0)
    required_item: None | str = Field(default=None)
    required_time: None | Time = Field(default=None)
    required_friendship: int = Field(default=0)

    def can_evolve(self, pokemon: Pokemon, owner: User, item: None | ItemType, time: Time) -> bool:
        if self.required_level > pokemon.level:
            return False

        if self.required_friendship > pokemon.friendship:
            return False

        if self.required_item and self.required_item != item:
            return False

        if self.required_time and self.required_time != time:
            return False

        if pokemon.gender not in self.to.available_genders:
            return False

        if pokemon.type == PokemonType.Mantyke:
            found = any(had.type in (PokemonType.Remoraid, PokemonType.Octillery) for had in owner.pokemons)
            if not found:
                return False

        return True


evolution_rules: dict[PokemonType, tuple[EvolutionRule, ...]] = {
    PokemonType.Bulbasaur: (EvolutionRule(to=PokemonType.Ivysaur, required_level=16),),
    PokemonType.Ivysaur: (EvolutionRule(to=PokemonType.Venusaur, required_level=32),),
    PokemonType.Charmander: (EvolutionRule(to=PokemonType.Charmeleon, required_level=16),),
    PokemonType.Charmeleon: (EvolutionRule(to=PokemonType.Charizard, required_level=36),),
    PokemonType.Squirtle: (EvolutionRule(to=PokemonType.Wartortle, required_level=16),),
    PokemonType.Wartortle: (EvolutionRule(to=PokemonType.Blastoise, required_level=36),),
    PokemonType.Caterpie: (EvolutionRule(to=PokemonType.Metapod, required_level=7),),
    PokemonType.Metapod: (EvolutionRule(to=PokemonType.Butterfree, required_level=10),),
    PokemonType.Weedle: (EvolutionRule(to=PokemonType.Kakuna, required_level=7),),
    PokemonType.Kakuna: (EvolutionRule(to=PokemonType.Beedrill, required_level=10),),
    PokemonType.Pidgey: (EvolutionRule(to=PokemonType.Pidgeotto, required_level=18),),
    PokemonType.Pidgeotto: (EvolutionRule(to=PokemonType.Pidgeot, required_level=36),),
    PokemonType.Rattata: (EvolutionRule(to=PokemonType.Raticate, required_level=20),),
    PokemonType.Spearow: (EvolutionRule(to=PokemonType.Fearow, required_level=20),),
    PokemonType.Ekans: (EvolutionRule(to=PokemonType.Arbok, required_level=22),),
    PokemonType.Pikachu: (EvolutionRule(to=PokemonType.Raichu, required_item=ItemType.THUNDER_STONE),),
    PokemonType.Sandshrew: (EvolutionRule(to=PokemonType.Sandslash, required_level=22),),
    PokemonType.Nidoran_female: (EvolutionRule(to=PokemonType.Nidorina, required_level=16),),
    PokemonType.Nidorina: (EvolutionRule(to=PokemonType.Nidoqueen, required_item=ItemType.MOON_STONE),),
    PokemonType.Nidoran_male: (EvolutionRule(to=PokemonType.Nidorino, required_level=16),),
    PokemonType.Nidorino: (EvolutionRule(to=PokemonType.Nidoking, required_item=ItemType.MOON_STONE),),
    PokemonType.Clefairy: (EvolutionRule(to=PokemonType.Clefable, required_item=ItemType.MOON_STONE),),
    PokemonType.Vulpix: (EvolutionRule(to=PokemonType.Ninetales, required_item=ItemType.FIRE_STONE),),
    PokemonType.Jigglypuff: (EvolutionRule(to=PokemonType.Wigglytuff, required_item=ItemType.MOON_STONE),),
    PokemonType.Zubat: (EvolutionRule(to=PokemonType.Golbat, required_level=22),),
    PokemonType.Golbat: (EvolutionRule(to=PokemonType.Crobat, required_friendship=220),),
    PokemonType.Oddish: (EvolutionRule(to=PokemonType.Gloom, required_level=22),),
    PokemonType.Gloom: (
        EvolutionRule(to=PokemonType.Vileplume, required_item=ItemType.LEAF_STONE),
        EvolutionRule(to=PokemonType.Bellossom, required_item=ItemType.SUN_STONE),
    ),
    PokemonType.Paras: (EvolutionRule(to=PokemonType.Parasect, required_level=24),),
    PokemonType.Venonat: (EvolutionRule(to=PokemonType.Venomoth, required_level=31),),
    PokemonType.Diglett: (EvolutionRule(to=PokemonType.Dugtrio, required_level=26),),
    PokemonType.Meowth: (EvolutionRule(to=PokemonType.Persian, required_level=28),),
    PokemonType.Psyduck: (EvolutionRule(to=PokemonType.Golduck, required_level=33),),
    PokemonType.Mankey: (EvolutionRule(to=PokemonType.Primeape, required_level=28),),
    PokemonType.Growlithe: (EvolutionRule(to=PokemonType.Arcanine, required_item=ItemType.FIRE_STONE),),
    PokemonType.Poliwag: (EvolutionRule(to=PokemonType.Poliwhirl, required_level=25),),
    PokemonType.Poliwhirl: (
        EvolutionRule(to=PokemonType.Poliwrath, required_item=ItemType.WATER_STONE),
        EvolutionRule(to=PokemonType.Politoed, required_item=ItemType.KINGS_ROCK),
    ),
    PokemonType.Abra: (EvolutionRule(to=PokemonType.Kadabra, required_level=16),),
    PokemonType.Kadabra: (EvolutionRule(to=PokemonType.Alakazam, required_item=ItemType.LINKING_CORD),),
    PokemonType.Machop: (EvolutionRule(to=PokemonType.Machoke, required_level=28),),
    PokemonType.Machoke: (EvolutionRule(to=PokemonType.Machamp, required_item=ItemType.LINKING_CORD),),
    PokemonType.Bellsprout: (EvolutionRule(to=PokemonType.Weepinbell, required_level=21),),
    PokemonType.Weepinbell: (EvolutionRule(to=PokemonType.Victreebel, required_item=ItemType.LEAF_STONE),),
    PokemonType.Tentacool: (EvolutionRule(to=PokemonType.Tentacruel, required_level=30),),
    PokemonType.Geodude: (EvolutionRule(to=PokemonType.Graveler, required_level=25),),
    PokemonType.Graveler: (EvolutionRule(to=PokemonType.Golem, required_item=ItemType.LINKING_CORD),),
    PokemonType.Ponyta: (EvolutionRule(to=PokemonType.Rapidash, required_level=40),),
    PokemonType.Slowpoke: (
        EvolutionRule(to=PokemonType.Slowbro, required_level=37),
        EvolutionRule(to=PokemonType.Slowking, required_item=ItemType.KINGS_ROCK),
    ),
    PokemonType.Magnemite: (EvolutionRule(to=PokemonType.Magneton, required_level=30),),
    PokemonType.Magneton: (EvolutionRule(to=PokemonType.Magnezone, required_item=ItemType.THUNDER_STONE),),
    PokemonType.Doduo: (EvolutionRule(to=PokemonType.Dodrio, required_level=31),),
    PokemonType.Seel: (EvolutionRule(to=PokemonType.Dewgong, required_level=34),),
    PokemonType.Grimer: (EvolutionRule(to=PokemonType.Muk, required_level=38),),
    PokemonType.Shellder: (EvolutionRule(to=PokemonType.Cloyster, required_item=ItemType.WATER_STONE),),
    PokemonType.Gastly: (EvolutionRule(to=PokemonType.Haunter, required_level=25),),
    PokemonType.Haunter: (EvolutionRule(to=PokemonType.Gengar, required_item=ItemType.LINKING_CORD),),
    PokemonType.Onix: (EvolutionRule(to=PokemonType.Steelix, required_item=ItemType.METAL_COAT),),
    PokemonType.Drowzee: (EvolutionRule(to=PokemonType.Hypno, required_level=26),),
    PokemonType.Krabby: (EvolutionRule(to=PokemonType.Kingler, required_level=28),),
    PokemonType.Voltorb: (EvolutionRule(to=PokemonType.Electrode, required_level=30),),
    PokemonType.Exeggcute: (EvolutionRule(to=PokemonType.Exeggutor, required_item=ItemType.LEAF_STONE),),
    PokemonType.Cubone: (EvolutionRule(to=PokemonType.Marowak, required_level=28),),
    PokemonType.Lickitung: (EvolutionRule(to=PokemonType.Lickilicky, required_level=33),),
    PokemonType.Koffing: (EvolutionRule(to=PokemonType.Weezing, required_level=35),),
    PokemonType.Rhyhorn: (EvolutionRule(to=PokemonType.Rhydon, required_level=42),),
    PokemonType.Rhydon: (EvolutionRule(to=PokemonType.Rhyperior, required_item=ItemType.PROTECTOR),),
    PokemonType.Chansey: (EvolutionRule(to=PokemonType.Blissey, required_friendship=220),),
    PokemonType.Tangela: (EvolutionRule(to=PokemonType.Tangrowth, required_level=33),),
    PokemonType.Horsea: (EvolutionRule(to=PokemonType.Seadra, required_level=32),),
    PokemonType.Seadra: (EvolutionRule(to=PokemonType.Kingdra, required_item=ItemType.DRAGON_SCALE),),
    PokemonType.Goldeen: (EvolutionRule(to=PokemonType.Seaking, required_level=33),),
    PokemonType.Staryu: (EvolutionRule(to=PokemonType.Starmie, required_item=ItemType.WATER_STONE),),
    PokemonType.Scyther: (EvolutionRule(to=PokemonType.Scizor, required_item=ItemType.METAL_COAT),),
    PokemonType.Electabuzz: (EvolutionRule(to=PokemonType.Electivire, required_item=ItemType.ELECTIRIZER),),
    PokemonType.Magmar: (EvolutionRule(to=PokemonType.Magmortar, required_item=ItemType.MAGMARIZER),),
    PokemonType.Magikarp: (EvolutionRule(to=PokemonType.Gyarados, required_level=20),),
    PokemonType.Eevee: (
        EvolutionRule(to=PokemonType.Vaporeon, required_item=ItemType.WATER_STONE),
        EvolutionRule(to=PokemonType.Jolteon, required_item=ItemType.THUNDER_STONE),
        EvolutionRule(to=PokemonType.Flareon, required_item=ItemType.FIRE_STONE),
        EvolutionRule(to=PokemonType.Espeon, required_friendship=160, required_time=Time.DAY),
        EvolutionRule(to=PokemonType.Umbreon, required_friendship=160, required_time=Time.NIGHT),
        EvolutionRule(to=PokemonType.Leafeon, required_item=ItemType.LEAF_STONE),
        EvolutionRule(to=PokemonType.Glaceon, required_item=ItemType.ICE_STONE),
    ),
    PokemonType.Porygon: (EvolutionRule(to=PokemonType.Porygon2, required_item=ItemType.UP_GRADE),),
    PokemonType.Omanyte: (EvolutionRule(to=PokemonType.Omastar, required_level=40),),
    PokemonType.Kabuto: (EvolutionRule(to=PokemonType.Kabutops, required_level=40),),
    PokemonType.Dratini: (EvolutionRule(to=PokemonType.Dragonair, required_level=30),),
    PokemonType.Dragonair: (EvolutionRule(to=PokemonType.Dragonite, required_level=55),),
    PokemonType.Chikorita: (EvolutionRule(to=PokemonType.Bayleef, required_level=16),),
    PokemonType.Bayleef: (EvolutionRule(to=PokemonType.Meganium, required_level=32),),
    PokemonType.Cyndaquil: (EvolutionRule(to=PokemonType.Quilava, required_level=14),),
    PokemonType.Quilava: (EvolutionRule(to=PokemonType.Typhlosion, required_level=36),),
    PokemonType.Totodile: (EvolutionRule(to=PokemonType.Croconaw, required_level=18),),
    PokemonType.Croconaw: (EvolutionRule(to=PokemonType.Feraligatr, required_level=30),),
    PokemonType.Sentret: (EvolutionRule(to=PokemonType.Furret, required_level=15),),
    PokemonType.Hoothoot: (EvolutionRule(to=PokemonType.Noctowl, required_level=20),),
    PokemonType.Ledyba: (EvolutionRule(to=PokemonType.Ledian, required_level=18),),
    PokemonType.Spinarak: (EvolutionRule(to=PokemonType.Ariados, required_level=22),),
    PokemonType.Chinchou: (EvolutionRule(to=PokemonType.Lanturn, required_level=27),),
    PokemonType.Pichu: (EvolutionRule(to=PokemonType.Pikachu, required_friendship=220),),
    PokemonType.Cleffa: (EvolutionRule(to=PokemonType.Clefairy, required_friendship=220),),
    PokemonType.Igglybuff: (EvolutionRule(to=PokemonType.Jigglypuff, required_friendship=220),),
    PokemonType.Togepi: (EvolutionRule(to=PokemonType.Togetic, required_friendship=220),),
    PokemonType.Togetic: (EvolutionRule(to=PokemonType.Togekiss, required_item=ItemType.SHINY_STONE),),
    PokemonType.Natu: (EvolutionRule(to=PokemonType.Xatu, required_level=25),),
    PokemonType.Mareep: (EvolutionRule(to=PokemonType.Flaaffy, required_level=15),),
    PokemonType.Flaaffy: (EvolutionRule(to=PokemonType.Ampharos, required_level=30),),
    PokemonType.Marill: (EvolutionRule(to=PokemonType.Azumarill, required_level=18),),
    PokemonType.Hoppip: (EvolutionRule(to=PokemonType.Skiploom, required_level=18),),
    PokemonType.Skiploom: (EvolutionRule(to=PokemonType.Jumpluff, required_level=27),),
    PokemonType.Aipom: (EvolutionRule(to=PokemonType.Ambipom, required_level=32),),
    PokemonType.Sunkern: (EvolutionRule(to=PokemonType.Sunflora, required_item=ItemType.SUN_STONE),),
    PokemonType.Wooper: (EvolutionRule(to=PokemonType.Quagsire, required_level=20),),
    PokemonType.Murkrow: (EvolutionRule(to=PokemonType.Honchkrow, required_item=ItemType.DUSK_STONE),),
    PokemonType.Misdreavus: (EvolutionRule(to=PokemonType.Mismagius, required_item=ItemType.DUSK_STONE),),
    PokemonType.Pineco: (EvolutionRule(to=PokemonType.Forretress, required_level=31),),
    PokemonType.Gligar: (
        EvolutionRule(to=PokemonType.Gliscor, required_item=ItemType.RAZOR_FANG, required_time=Time.NIGHT),
    ),
    PokemonType.Snubbull: (EvolutionRule(to=PokemonType.Granbull, required_level=23),),
    PokemonType.Sneasel: (
        EvolutionRule(to=PokemonType.Weavile, required_item=ItemType.RAZOR_CLAW, required_time=Time.NIGHT),
    ),
    PokemonType.Teddiursa: (EvolutionRule(to=PokemonType.Ursaring, required_level=30),),
    PokemonType.Slugma: (EvolutionRule(to=PokemonType.Magcargo, required_level=38),),
    PokemonType.Swinub: (EvolutionRule(to=PokemonType.Piloswine, required_level=33),),
    PokemonType.Piloswine: (EvolutionRule(to=PokemonType.Mamoswine, required_level=34),),
    PokemonType.Remoraid: (EvolutionRule(to=PokemonType.Octillery, required_level=25),),
    PokemonType.Houndour: (EvolutionRule(to=PokemonType.Houndoom, required_level=24),),
    PokemonType.Phanpy: (EvolutionRule(to=PokemonType.Donphan, required_level=25),),
    PokemonType.Porygon2: (EvolutionRule(to=PokemonType.PorygonZ, required_item=ItemType.DUBIOUS_DISC),),
    PokemonType.Tyrogue: (
        EvolutionRule(to=PokemonType.Hitmonlee, required_level=20),
        EvolutionRule(to=PokemonType.Hitmonchan, required_level=20),
        EvolutionRule(to=PokemonType.Hitmontop, required_level=20),
    ),  # random
    PokemonType.Smoochum: (EvolutionRule(to=PokemonType.Jynx, required_level=30),),
    PokemonType.Elekid: (EvolutionRule(to=PokemonType.Electabuzz, required_level=30),),
    PokemonType.Magby: (EvolutionRule(to=PokemonType.Magmar, required_level=30),),
    PokemonType.Larvitar: (EvolutionRule(to=PokemonType.Pupitar, required_level=30),),
    PokemonType.Pupitar: (EvolutionRule(to=PokemonType.Tyranitar, required_level=55),),
    PokemonType.Treecko: (EvolutionRule(to=PokemonType.Grovyle, required_level=16),),
    PokemonType.Grovyle: (EvolutionRule(to=PokemonType.Sceptile, required_level=36),),
    PokemonType.Torchic: (EvolutionRule(to=PokemonType.Combusken, required_level=16),),
    PokemonType.Combusken: (EvolutionRule(to=PokemonType.Blaziken, required_level=36),),
    PokemonType.Mudkip: (EvolutionRule(to=PokemonType.Marshtomp, required_level=16),),
    PokemonType.Marshtomp: (EvolutionRule(to=PokemonType.Swampert, required_level=36),),
    PokemonType.Poochyena: (EvolutionRule(to=PokemonType.Mightyena, required_level=18),),
    PokemonType.Zigzagoon: (EvolutionRule(to=PokemonType.Linoone, required_level=20),),
    PokemonType.Wurmple: (
        EvolutionRule(to=PokemonType.Silcoon, required_level=7),
        EvolutionRule(to=PokemonType.Cascoon, required_level=7),
    ),  # random
    PokemonType.Silcoon: (EvolutionRule(to=PokemonType.Beautifly, required_level=10),),
    PokemonType.Cascoon: (EvolutionRule(to=PokemonType.Dustox, required_level=10),),
    PokemonType.Lotad: (EvolutionRule(to=PokemonType.Lombre, required_level=14),),
    PokemonType.Lombre: (EvolutionRule(to=PokemonType.Ludicolo, required_item=ItemType.WATER_STONE),),
    PokemonType.Seedot: (EvolutionRule(to=PokemonType.Nuzleaf, required_level=14),),
    PokemonType.Nuzleaf: (EvolutionRule(to=PokemonType.Shiftry, required_item=ItemType.LEAF_STONE),),
    PokemonType.Taillow: (EvolutionRule(to=PokemonType.Swellow, required_level=22),),
    PokemonType.Wingull: (EvolutionRule(to=PokemonType.Pelipper, required_level=25),),
    PokemonType.Ralts: (EvolutionRule(to=PokemonType.Kirlia, required_level=20),),
    PokemonType.Kirlia: (
        EvolutionRule(to=PokemonType.Gardevoir, required_level=30),
        EvolutionRule(to=PokemonType.Gallade, required_item=ItemType.DAWN_STONE),
    ),
    PokemonType.Surskit: (EvolutionRule(to=PokemonType.Masquerain, required_level=22),),
    PokemonType.Shroomish: (EvolutionRule(to=PokemonType.Breloom, required_level=23),),
    PokemonType.Slakoth: (EvolutionRule(to=PokemonType.Vigoroth, required_level=18),),
    PokemonType.Vigoroth: (EvolutionRule(to=PokemonType.Slaking, required_level=36),),
    PokemonType.Nincada: (EvolutionRule(to=PokemonType.Ninjask, required_level=20),),  # give user Shedinja too
    PokemonType.Whismur: (EvolutionRule(to=PokemonType.Loudred, required_level=20),),
    PokemonType.Loudred: (EvolutionRule(to=PokemonType.Exploud, required_level=40),),
    PokemonType.Makuhita: (EvolutionRule(to=PokemonType.Hariyama, required_level=24),),
    PokemonType.Azurill: (EvolutionRule(to=PokemonType.Marill, required_friendship=220),),
    PokemonType.Nosepass: (EvolutionRule(to=PokemonType.Probopass, required_item=ItemType.THUNDER_STONE),),
    PokemonType.Skitty: (EvolutionRule(to=PokemonType.Delcatty, required_item=ItemType.MOON_STONE),),
    PokemonType.Aron: (EvolutionRule(to=PokemonType.Lairon, required_level=32),),
    PokemonType.Lairon: (EvolutionRule(to=PokemonType.Aggron, required_level=42),),
    PokemonType.Meditite: (EvolutionRule(to=PokemonType.Medicham, required_level=37),),
    PokemonType.Electrike: (EvolutionRule(to=PokemonType.Manectric, required_level=26),),
    PokemonType.Roselia: (EvolutionRule(to=PokemonType.Roserade, required_item=ItemType.SHINY_STONE),),
    PokemonType.Gulpin: (EvolutionRule(to=PokemonType.Swalot, required_level=26),),
    PokemonType.Carvanha: (EvolutionRule(to=PokemonType.Sharpedo, required_level=30),),
    PokemonType.Wailmer: (EvolutionRule(to=PokemonType.Wailord, required_level=40),),
    PokemonType.Numel: (EvolutionRule(to=PokemonType.Camerupt, required_level=33),),
    PokemonType.Spoink: (EvolutionRule(to=PokemonType.Grumpig, required_level=32),),
    PokemonType.Trapinch: (EvolutionRule(to=PokemonType.Vibrava, required_level=35),),
    PokemonType.Vibrava: (EvolutionRule(to=PokemonType.Flygon, required_level=45),),
    PokemonType.Cacnea: (EvolutionRule(to=PokemonType.Cacturne, required_level=32),),
    PokemonType.Swablu: (EvolutionRule(to=PokemonType.Altaria, required_level=35),),
    PokemonType.Barboach: (EvolutionRule(to=PokemonType.Whiscash, required_level=30),),
    PokemonType.Corphish: (EvolutionRule(to=PokemonType.Crawdaunt, required_level=30),),
    PokemonType.Baltoy: (EvolutionRule(to=PokemonType.Claydol, required_level=36),),
    PokemonType.Lileep: (EvolutionRule(to=PokemonType.Cradily, required_level=40),),
    PokemonType.Anorith: (EvolutionRule(to=PokemonType.Armaldo, required_level=40),),
    PokemonType.Feebas: (EvolutionRule(to=PokemonType.Milotic, required_item=ItemType.PRISM_SCALE),),
    PokemonType.Shuppet: (EvolutionRule(to=PokemonType.Banette, required_level=37),),
    PokemonType.Duskull: (EvolutionRule(to=PokemonType.Dusclops, required_level=37),),
    PokemonType.Dusclops: (EvolutionRule(to=PokemonType.Dusknoir, required_item=ItemType.REAPER_CLOTH),),
    PokemonType.Wynaut: (EvolutionRule(to=PokemonType.Wobbuffet, required_level=15),),
    PokemonType.Snorunt: (
        EvolutionRule(to=PokemonType.Glalie, required_level=42),
        EvolutionRule(to=PokemonType.Froslass, required_item=ItemType.DAWN_STONE),
    ),
    PokemonType.Spheal: (EvolutionRule(to=PokemonType.Sealeo, required_level=32),),
    PokemonType.Sealeo: (EvolutionRule(to=PokemonType.Walrein, required_level=44),),
    PokemonType.Clamperl: (
        EvolutionRule(to=PokemonType.Huntail, required_item=ItemType.DEEP_SEA_TOOTH),
        EvolutionRule(to=PokemonType.Gorebyss, required_item=ItemType.DEEP_SEA_SCALE),
    ),
    PokemonType.Bagon: (EvolutionRule(to=PokemonType.Shelgon, required_level=30),),
    PokemonType.Shelgon: (EvolutionRule(to=PokemonType.Salamence, required_level=50),),
    PokemonType.Beldum: (EvolutionRule(to=PokemonType.Metang, required_level=20),),
    PokemonType.Metang: (EvolutionRule(to=PokemonType.Metagross, required_level=45),),
    PokemonType.Turtwig: (EvolutionRule(to=PokemonType.Grotle, required_level=18),),
    PokemonType.Grotle: (EvolutionRule(to=PokemonType.Torterra, required_level=32),),
    PokemonType.Chimchar: (EvolutionRule(to=PokemonType.Monferno, required_level=14),),
    PokemonType.Monferno: (EvolutionRule(to=PokemonType.Infernape, required_level=36),),
    PokemonType.Piplup: (EvolutionRule(to=PokemonType.Prinplup, required_level=16),),
    PokemonType.Prinplup: (EvolutionRule(to=PokemonType.Empoleon, required_level=36),),
    PokemonType.Starly: (EvolutionRule(to=PokemonType.Staravia, required_level=14),),
    PokemonType.Staravia: (EvolutionRule(to=PokemonType.Staraptor, required_level=34),),
    PokemonType.Bidoof: (EvolutionRule(to=PokemonType.Bibarel, required_level=15),),
    PokemonType.Kricketot: (EvolutionRule(to=PokemonType.Kricketune, required_level=10),),
    PokemonType.Shinx: (EvolutionRule(to=PokemonType.Luxio, required_level=15),),
    PokemonType.Luxio: (EvolutionRule(to=PokemonType.Luxray, required_level=30),),
    PokemonType.Budew: (EvolutionRule(to=PokemonType.Roselia, required_friendship=160, required_time=Time.DAY),),
    PokemonType.Cranidos: (EvolutionRule(to=PokemonType.Rampardos, required_level=30),),
    PokemonType.Shieldon: (EvolutionRule(to=PokemonType.Bastiodon, required_level=30),),
    PokemonType.Burmy: (
        EvolutionRule(to=PokemonType.Wormadam, required_level=20),
        EvolutionRule(to=PokemonType.Mothim, required_level=20),
    ),
    PokemonType.Combee: (EvolutionRule(to=PokemonType.Vespiquen, required_level=21),),
    PokemonType.Buizel: (EvolutionRule(to=PokemonType.Floatzel, required_level=26),),
    PokemonType.Cherubi: (EvolutionRule(to=PokemonType.Cherrim, required_level=25),),
    PokemonType.Shellos: (EvolutionRule(to=PokemonType.Gastrodon, required_level=30),),
    PokemonType.Drifloon: (EvolutionRule(to=PokemonType.Drifblim, required_level=28),),
    PokemonType.Buneary: (EvolutionRule(to=PokemonType.Lopunny, required_friendship=220),),
    PokemonType.Glameow: (EvolutionRule(to=PokemonType.Purugly, required_level=38),),
    PokemonType.Chingling: (
        EvolutionRule(to=PokemonType.Chimecho, required_friendship=220, required_time=Time.NIGHT),
    ),
    PokemonType.Stunky: (EvolutionRule(to=PokemonType.Skuntank, required_level=34),),
    PokemonType.Bronzor: (EvolutionRule(to=PokemonType.Bronzong, required_level=33),),
    PokemonType.Bonsly: (EvolutionRule(to=PokemonType.Sudowoodo, required_level=15),),
    PokemonType.MimeJr: (EvolutionRule(to=PokemonType.MrMime, required_level=18),),
    PokemonType.Happiny: (EvolutionRule(to=PokemonType.Chansey, required_item=ItemType.OVAL_STONE),),
    PokemonType.Gible: (EvolutionRule(to=PokemonType.Gabite, required_level=24),),
    PokemonType.Gabite: (EvolutionRule(to=PokemonType.Garchomp, required_level=48),),
    PokemonType.Munchlax: (EvolutionRule(to=PokemonType.Snorlax, required_friendship=220),),
    PokemonType.Riolu: (EvolutionRule(to=PokemonType.Lucario, required_friendship=220, required_time=Time.DAY),),
    PokemonType.Hippopotas: (EvolutionRule(to=PokemonType.Hippowdon, required_level=34),),
    PokemonType.Skorupi: (EvolutionRule(to=PokemonType.Drapion, required_level=40),),
    PokemonType.Croagunk: (EvolutionRule(to=PokemonType.Toxicroak, required_level=37),),
    PokemonType.Finneon: (EvolutionRule(to=PokemonType.Lumineon, required_level=31),),
    PokemonType.Mantyke: (EvolutionRule(to=PokemonType.Mantine),),  # Condition that user have Remoraid
}

evolution_line_cnts: dict[PokemonType, int] = {
    PokemonType.Bulbasaur: 1,
    PokemonType.Charmander: 1,
    PokemonType.Squirtle: 1,
    PokemonType.Caterpie: 1,
    PokemonType.Weedle: 1,
    PokemonType.Pidgey: 1,
    PokemonType.Rattata: 1,
    PokemonType.Spearow: 1,
    PokemonType.Ekans: 1,
    PokemonType.Sandshrew: 1,
    PokemonType.Nidoran_female: 1,
    PokemonType.Nidoran_male: 1,
    PokemonType.Vulpix: 1,
    PokemonType.Zubat: 1,
    PokemonType.Oddish: 2,
    PokemonType.Paras: 1,
    PokemonType.Venonat: 1,
    PokemonType.Diglett: 1,
    PokemonType.Meowth: 1,
    PokemonType.Psyduck: 1,
    PokemonType.Mankey: 1,
    PokemonType.Growlithe: 1,
    PokemonType.Poliwag: 2,
    PokemonType.Abra: 1,
    PokemonType.Machop: 1,
    PokemonType.Bellsprout: 1,
    PokemonType.Tentacool: 1,
    PokemonType.Geodude: 1,
    PokemonType.Ponyta: 1,
    PokemonType.Slowpoke: 2,
    PokemonType.Magnemite: 1,
    PokemonType.Farfetchd: 1,
    PokemonType.Doduo: 1,
    PokemonType.Seel: 1,
    PokemonType.Grimer: 1,
    PokemonType.Shellder: 1,
    PokemonType.Gastly: 1,
    PokemonType.Onix: 1,
    PokemonType.Drowzee: 1,
    PokemonType.Krabby: 1,
    PokemonType.Voltorb: 1,
    PokemonType.Exeggcute: 1,
    PokemonType.Cubone: 1,
    PokemonType.Lickitung: 1,
    PokemonType.Koffing: 1,
    PokemonType.Rhyhorn: 1,
    PokemonType.Tangela: 1,
    PokemonType.Kangaskhan: 1,
    PokemonType.Horsea: 1,
    PokemonType.Goldeen: 1,
    PokemonType.Staryu: 1,
    PokemonType.Scyther: 1,
    PokemonType.Pinsir: 1,
    PokemonType.Tauros: 1,
    PokemonType.Magikarp: 1,
    PokemonType.Lapras: 1,
    PokemonType.Ditto: 1,
    PokemonType.Eevee: 7,
    PokemonType.Porygon: 1,
    PokemonType.Omanyte: 1,
    PokemonType.Kabuto: 1,
    PokemonType.Aerodactyl: 1,
    PokemonType.Articuno: 1,
    PokemonType.Zapdos: 1,
    PokemonType.Moltres: 1,
    PokemonType.Dratini: 1,
    PokemonType.Mewtwo: 1,
    PokemonType.Mew: 1,
    PokemonType.Chikorita: 1,
    PokemonType.Cyndaquil: 1,
    PokemonType.Totodile: 1,
    PokemonType.Sentret: 1,
    PokemonType.Hoothoot: 1,
    PokemonType.Ledyba: 1,
    PokemonType.Spinarak: 1,
    PokemonType.Chinchou: 1,
    PokemonType.Pichu: 1,
    PokemonType.Cleffa: 1,
    PokemonType.Igglybuff: 1,
    PokemonType.Togepi: 1,
    PokemonType.Natu: 1,
    PokemonType.Mareep: 1,
    PokemonType.Hoppip: 1,
    PokemonType.Aipom: 1,
    PokemonType.Sunkern: 1,
    PokemonType.Yanma: 1,
    PokemonType.Wooper: 1,
    PokemonType.Murkrow: 1,
    PokemonType.Misdreavus: 1,
    PokemonType.Unown: 1,
    PokemonType.Girafarig: 1,
    PokemonType.Pineco: 1,
    PokemonType.Dunsparce: 1,
    PokemonType.Gligar: 1,
    PokemonType.Snubbull: 1,
    PokemonType.Qwilfish: 1,
    PokemonType.Shuckle: 1,
    PokemonType.Heracross: 1,
    PokemonType.Sneasel: 1,
    PokemonType.Teddiursa: 1,
    PokemonType.Slugma: 1,
    PokemonType.Swinub: 1,
    PokemonType.Corsola: 1,
    PokemonType.Remoraid: 1,
    PokemonType.Delibird: 1,
    PokemonType.Skarmory: 1,
    PokemonType.Houndour: 1,
    PokemonType.Phanpy: 1,
    PokemonType.Stantler: 1,
    PokemonType.Smeargle: 1,
    PokemonType.Tyrogue: 3,
    PokemonType.Smoochum: 1,
    PokemonType.Elekid: 1,
    PokemonType.Magby: 1,
    PokemonType.Miltank: 1,
    PokemonType.Raikou: 1,
    PokemonType.Entei: 1,
    PokemonType.Suicune: 1,
    PokemonType.Larvitar: 1,
    PokemonType.Lugia: 1,
    PokemonType.HoOh: 1,
    PokemonType.Celebi: 1,
    PokemonType.Treecko: 1,
    PokemonType.Torchic: 1,
    PokemonType.Mudkip: 1,
    PokemonType.Poochyena: 1,
    PokemonType.Zigzagoon: 1,
    PokemonType.Wurmple: 2,
    PokemonType.Lotad: 1,
    PokemonType.Seedot: 1,
    PokemonType.Taillow: 1,
    PokemonType.Wingull: 1,
    PokemonType.Ralts: 2,
    PokemonType.Surskit: 1,
    PokemonType.Shroomish: 1,
    PokemonType.Slakoth: 1,
    PokemonType.Nincada: 1,
    PokemonType.Whismur: 1,
    PokemonType.Makuhita: 1,
    PokemonType.Azurill: 1,
    PokemonType.Nosepass: 1,
    PokemonType.Skitty: 1,
    PokemonType.Sableye: 1,
    PokemonType.Mawile: 1,
    PokemonType.Aron: 1,
    PokemonType.Meditite: 1,
    PokemonType.Electrike: 1,
    PokemonType.Plusle: 1,
    PokemonType.Minun: 1,
    PokemonType.Volbeat: 1,
    PokemonType.Illumise: 1,
    PokemonType.Gulpin: 1,
    PokemonType.Carvanha: 1,
    PokemonType.Wailmer: 1,
    PokemonType.Numel: 1,
    PokemonType.Torkoal: 1,
    PokemonType.Spoink: 1,
    PokemonType.Spinda: 1,
    PokemonType.Trapinch: 1,
    PokemonType.Cacnea: 1,
    PokemonType.Swablu: 1,
    PokemonType.Zangoose: 1,
    PokemonType.Seviper: 1,
    PokemonType.Lunatone: 1,
    PokemonType.Solrock: 1,
    PokemonType.Barboach: 1,
    PokemonType.Corphish: 1,
    PokemonType.Baltoy: 1,
    PokemonType.Lileep: 1,
    PokemonType.Anorith: 1,
    PokemonType.Feebas: 1,
    PokemonType.Castform: 1,
    PokemonType.Kecleon: 1,
    PokemonType.Shuppet: 1,
    PokemonType.Duskull: 1,
    PokemonType.Tropius: 1,
    PokemonType.Absol: 1,
    PokemonType.Wynaut: 1,
    PokemonType.Snorunt: 2,
    PokemonType.Spheal: 1,
    PokemonType.Clamperl: 2,
    PokemonType.Relicanth: 1,
    PokemonType.Luvdisc: 1,
    PokemonType.Bagon: 1,
    PokemonType.Beldum: 1,
    PokemonType.Regirock: 1,
    PokemonType.Regice: 1,
    PokemonType.Registeel: 1,
    PokemonType.Latias: 1,
    PokemonType.Latios: 1,
    PokemonType.Kyogre: 1,
    PokemonType.Groudon: 1,
    PokemonType.Rayquaza: 1,
    PokemonType.Jirachi: 1,
    PokemonType.Deoxys: 1,
    PokemonType.Turtwig: 1,
    PokemonType.Chimchar: 1,
    PokemonType.Piplup: 1,
    PokemonType.Starly: 1,
    PokemonType.Bidoof: 1,
    PokemonType.Kricketot: 1,
    PokemonType.Shinx: 1,
    PokemonType.Budew: 1,
    PokemonType.Cranidos: 1,
    PokemonType.Shieldon: 1,
    PokemonType.Burmy: 2,
    PokemonType.Combee: 1,
    PokemonType.Pachirisu: 1,
    PokemonType.Buizel: 1,
    PokemonType.Cherubi: 1,
    PokemonType.Shellos: 1,
    PokemonType.Drifloon: 1,
    PokemonType.Buneary: 1,
    PokemonType.Glameow: 1,
    PokemonType.Chingling: 1,
    PokemonType.Stunky: 1,
    PokemonType.Bronzor: 1,
    PokemonType.Bonsly: 1,
    PokemonType.MimeJr: 1,
    PokemonType.Happiny: 1,
    PokemonType.Chatot: 1,
    PokemonType.Spiritomb: 1,
    PokemonType.Gible: 1,
    PokemonType.Munchlax: 1,
    PokemonType.Riolu: 1,
    PokemonType.Hippopotas: 1,
    PokemonType.Skorupi: 1,
    PokemonType.Croagunk: 1,
    PokemonType.Carnivine: 1,
    PokemonType.Finneon: 1,
    PokemonType.Mantyke: 1,
    PokemonType.Snover: 1,
    PokemonType.Abomasnow: 1,
    PokemonType.Yanmega: 1,
    PokemonType.Rotom: 1,
    PokemonType.Uxie: 1,
    PokemonType.Mesprit: 1,
    PokemonType.Azelf: 1,
    PokemonType.Dialga: 1,
    PokemonType.Palkia: 1,
    PokemonType.Heatran: 1,
    PokemonType.Regigigas: 1,
    PokemonType.Giratina: 1,
    PokemonType.Cresselia: 1,
    PokemonType.Phione: 1,
    PokemonType.Manaphy: 1,
    PokemonType.Darkrai: 1,
    PokemonType.Shaymin: 1,
    PokemonType.Arceus: 1,
}
